theme: ["hugo-theme-stack", "hugo-notice"]

# 添加这些配置
params:
  mainSections:
    - post
  featuredImageField: image
  rssFullContent: true
  favicon:

  footer:
    since: 2020
    customText:

  dateFormat:
    published: Jan 02, 2006
    lastUpdated: Jan 02, 2006 15:04 MST

  sidebar:
    emoji: 
    subtitle: Lorem ipsum dolor sit amet.
    avatar:
      enabled: true
      local: true
      src: img/avatar.png 